name: Build

on:
  pull_request:
  push:
    branches: ['**']

jobs:
  nextflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: MillironX/setup-nextflow@v1
      # On validates flow:
      #   Confirms workflow is valid
      #   Confirms all containers are available
      - name: Validate bam input
        run: |
          nextflow run main.nf \
            -profile test -stub-run \
            --pairs test_files/colo-cram.csv \
            --outdir full_results
      - name: Validate counts input
        run: |
          nextflow run main.nf \
            -profile test -stub-run \
            --counts \
            --pairs test_files/colo-counts.csv \
            --outdir count_results
